---
- name: Run apt and install SumoLogic Collector
  include: apt_install.yml
  when: ansible_os_family == 'Debian' and ansible_distribution == 'Ubuntu'

- name: Run yum and install SumoLogic Collector
  include: yum_install.yml
  when: ansible_os_family == 'RedHat'

- name: Collector Setup
  include: collector_setup.yml
  when: sumologic_configure_collector == true

- name: Monit setup
  template:
    src: "monit-sumocollector.cfg.j2"
    dest: "/etc/monit/conf.d/sumocollector.cfg"
    owner: root
    group: root
    mode: 0600
  when: sumologic_use_monit
